### PR TITLE
SDL_image 2.6.0

### PR DESCRIPTION
**Pull request by h-vetinari**
Had some SVG failures in https://github.com/conda-forge/staged-recipes/pull/19665, saw a new upstream release - let's try building for it. :)

Happily, upstream now supports CMake builds natively. 🥳

### CODE REVIEW

**Comment by carterbox** [comment]
Try this please. I don't have permission to your branch otherwise I would have just pushed the following commit directly. This patch adds another patch (meta-patch!) which removes the custom find webp cmake file.

```
From 84ae7986769affec8c87e72f6187a109437b5002 Mon Sep 17 00:00:00 2001
From: Daniel Ching <carterbox@users.noreply.github.com>
Date: Fri, 22 Jul 2022 19:10:24 -0500
Subject: [PATCH] BLD: Use CMake artifacts isntead of custom findwebp

---
 recipe/meta.yaml                                |   1 +
 ...ook-for-conda-forge-variant-of-libwebp.patch | Bin 747 -> 746 bytes
 .../patches/0002-remove-custom-find-webp.patch  | Bin 0 -> 1544 bytes
 3 files changed, 1 insertion(+)
 create mode 100644 recipe/patches/0002-remove-custom-find-webp.patch

diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index a3fdf62..6990cb7 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -9,6 +9,7 @@ source:
   sha256: fb61d96446cdb1668f837dd7ba1d22d6631755d5dda86580a1cb5aefa3e62278
   patches:
     - patches/0001-look-for-conda-forge-variant-of-libwebp.patch
+    - patches/0002-remove-custom-find-webp.patch  # [win]
 
 build:
   number: 0
diff --git a/recipe/patches/0001-look-for-conda-forge-variant-of-libwebp.patch b/recipe/patches/0001-look-for-conda-forge-variant-of-libwebp.patch
index 2fc8899e979d90bc1e723ada30a3996bfe479bf4..154150bfda5b7da2559a238072a8266786e79297 100644
GIT binary patch
delta 27
icmaFO`igbKbtYjhBRyktJp;Y+%)FHR@?t$hE-nCrEeKiw

delta 28
jcmaFG`kHmabtVx7E+ai-b3FsS^31%H{PJQwLoO}=i985<

diff --git a/recipe/patches/0002-remove-custom-find-webp.patch b/recipe/patches/0002-remove-custom-find-webp.patch
new file mode 100644
index 0000000000000000000000000000000000000000..70d498073666376510a1bccf91f69efe593b7da3
GIT binary patch
literal 1544
zcmbtUO;e*l6uk2*rcxeaMM#XUQBNY7#Ho;h9f<CprbrkfD<Kr1n=Q-#zHj(2m_+xm
zTu2_Tn||GI@WUWLs=5qw<aLdy_aw|P%QG$C<Y>NAP{P<38#FleF24l>O*<c4_2=FK
zo%VVc=jV#5s(Tztr_<Tzxw%2=#pT(_0CnW;0zn}R+Ro7Ilc_$&oKVNrP4iem&8v0v
zYE1PB=EjUMOkI9UsLp=!Az^P_3FhI-TMA<x2jNm%tYDbde=yvOGz-`9L85}ZI|4(Z
zaQ<r(l}(D;l)LTuE#^tp@!l}RjtlZ#Vo?Nx*^@E186J@zZw<|cHMK1Yqat6th^QRq
zSn->o9eNE|eyFVYA`-dqQ4mG~t=7J%vn!MBpIu${eP7dh<yA#`kV*#I1y$YnIf@jS
z=;_H>A9Z>sJ&03L!*~%r`=Tv9vc1I<1as$sUBb!X=B2)#F0*4rRn!1FIM|qa>7TZ=
ziksw?L9nHrRG(r8$-1I$`x7sJESm{6%-IlgTX*kv5g>2@Q)-VDG!uCVlExAfbIX<i
zIH=V^hHl(p<hYE`F>2vWo_c7pUM141b&|s-WM~}}LRy86cQTXENu`;9)K9pgFn&Vi
zn4$QRYGmr;uW5qFTkcR4E+(bX{IPJFXO-351Fwt0OM@8xJ|hed`Mu6cYirAk@!<G1
zEiHx(15`RUvSxG$CArA5NG%t+IvZmbJ&3t|eJzu!p35H3--f$wKr=d_)&oTZ7M!`b
zW|Ro<mFJ)sZb`aMM4E$N?FQCnmW`PUUY9Z?NM1D;H!b7+U`aXkba1pjoKQkt%tpE)
zKRD&Y@F~HDYq287qt^mlKa&ggIm6yYRp`22g!(yrcZVwU$MQem)!sCrdvC3h5ixv2
J+VH3T@fQ%dyKVpg

literal 0
HcmV?d00001

-- 
2.24.0.windows.1

```

**Comment by h-vetinari** [comment]
> Try this please

Thank you very much for helping with this! My first question is: why do we need a binary patch? Can this not be a text file or sequence of instructions to apply? Because I'd have no idea how to rebase this when the next version comes along

**Comment by carterbox** [comment]
This patch does not contain binaries. This is a patch in txt format that adds a new file which is also a patch in text form. If you apply the patch, the new file gets deserialized.

**Comment by h-vetinari** [comment]
> This patch does not contain binaries. This is a patch in txt format that adds a new file which is also a patch in text form. If you apply the patch, the new file gets deserialized.

Ok cool, but that still makes the thing completely inscrutable. Git can handle patches containing `.patch` files just fine though, so my question is why we cannot just patch in the _application_ of another patch in text form (that's either added by the outer patch itself, or gets copied in from the recipe)

**Comment by h-vetinari** [comment]
OK, I finally understood now that this was not a meta-patch in the sense that it was intended for this feedstock, not the patch-within-patch that's occasionally necessary for certain builds. I was just confused because the same effect could have been achieved more directly by just opening a PR against https://github.com/h-vetinari/sdl2_image-feedstock/tree/bump 😅

**Comment by carterbox** [comment]
> have been achieved more directly by just opening a PR

🤦🏼 That's very true.

Anyways, it looks like my patch succeeded in doing what I intended. There are other issues on this PR unrelated to libwebp-base which you need to fix. Please close https://github.com/conda-forge/libwebp-base-feedstock/pull/15 if it's not needed anymore or we can leave it open and incorporate it into the next release.

**Comment by h-vetinari** [comment]
Alrighty @carterbox, thanks for the input here, this worked! 🥳 

Anything else from your POV that needs to happen either in this PR or in https://github.com/conda-forge/libwebp-base-feedstock/pull/15?

**Comment by h-vetinari** [comment]
> Anyways, it looks like my patch succeeded in doing what I intended. There are other issues on this PR unrelated to libwebp-base which you need to fix. Please close [conda-forge/libwebp-base-feedstock#15](https://github.com/conda-forge/libwebp-base-feedstock/pull/15) if it's not needed anymore or we can leave it open and incorporate it into the next release.

Ah, just saw that you had edited this into your comment (makes it harder to follow because edits don't generate notifications). Happy to keep https://github.com/conda-forge/libwebp-base-feedstock/pull/15 as a clean-up for the next release.

**Comment by h-vetinari** [comment]
@conda-forge/sdl2_image PTAL

Upstream switched to native CMake, and I'd need this for https://github.com/conda-forge/staged-recipes/pull/19665 🙃

**Comment by carterbox** [comment]
I have no more opinions on this PR. Good luck, @h-vetinari !

**Pull request merged**
